# PostgreSQL configuration for development environment
development:
  adapter: postgresql
  encoding: unicode
  database: blogapp_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: EbunAyo23
  host: localhost

# PostgreSQL configuration for test environment
test:
  adapter: postgresql
  encoding: unicode
  database: blogapp_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: EbunAyo23
  host: localhost

# PostgreSQL configuration for production environment
production:
  adapter: postgresql
  encoding: unicode
  database: blogapp_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: EbunAyo23
  host: your_host
